### ISSUE TITLE
Instruction needed for students to navigate the graph

### ISSUE THREAD

**Issue by Qiaojuan-Tu** [EducationShinyAppTeam/QQ_Plot#2]
A few sentence on the page to describe how the navigation works and what the different numbers mean would be helpful to students using the program.

**Comment by neilhatfield** [comment]
@NurulSyafiqah-pixel @JingFu1 @Phichchaya27 

Do you think that #7 addresses this issue?

**Comment by JingFu1** [comment]
I think the instructions on the overview page are ok to guide users to explore but there are lacking of necessary explanations of some numbers we have to choose on the explore page, like Percentage under left mode, I do not know what’s the meaning.
