### ISSUE TITLE
Wordings Improvement

### ISSUE THREAD

**Issue by NurulSyafiqah-pixel** [EducationShinyAppTeam/QQ_Plot#6]
I'd like to propose an improvement to the sentences below: 

Original:

This application is designed to examine Q-Q (Quantile-Quantile) plots. The Q-Q plot, or quantile-quantile plot, is a graphical tool to help us assess if a set of data plausibly came from some theoretical distribution such as a normal (Gaussian) distribution.

To:

This application is designed to examine Q-Q (Quantile-Quantile) plots: a graphical tool to help us assess if a set of data plausibly came from some theoretical distribution such as a normal (Gaussian) distribution.

**Comment by neilhatfield** [comment]
I like the intent behind the wording fix. Let's try to put the user center stage. How about this modification?

This application is designed to help the user explore how a QQ (Quantile-Quantile) plot can be used as a graphical tool to assess whether a particular set of observations reasonably follow a particular distribution such as a Gaussian ("normal").
